### ISSUE TITLE
Pitch

### ISSUE THREAD

**Issue by GuiBarradas** [GuiBarradas/projetoIntegrador_CIEDS#1]
Caros, terminei toda a correção e formatação do texto. Retirei todos os erros gramaticais, como alguns erros de concordância, uso da vírgula e etc. Adicionei uma tela separada para cada etapa. Ali os respectivos problemas serão especificados: Tutoriais, dicas e um passo a passo para o usuário conseguir desenvolver uma solução para o que foi proposto. 

Nosso trabalho agora é discutir ideias para como fazer essas telas individuais de um jeito bom, padronizado e interativo, para que possa realmente substituir o modelo de treinamento atual em nossa empresa.

Pensem em algo interativo, que vocês conseguiriam entender de forma leve e _"clean"_.

Para finalizar, gostaria de saber: Vocês tem disponibilidade para uma call no Discord para tratarmos esse assunto? Um ou dois _"brainstormings"_.

Lembrando, a apresentação é daqui a **2 semanas.**

**Comment by Dayanepereira** [comment]
Poderíamos também adicionar uns checklist para o usuário poder se organizar no que já foi realizado e também dar atenção as dúvidas e dificuldades que nós tivemos ao longo do treinamento. 
Em relação à disponibilidade sempre que precisar é só ligar.

**Comment by GuiBarradas** [comment]
Fechado.
