### ISSUE TITLE
Orientação

### ISSUE THREAD

**Issue by GuiBarradas** [GuiBarradas/projetoIntegrador_CIEDS#7]
Etapas finalizadas: 1, 2, 3, 4, 5, 6, 7, 8, 9 e 10 (MEXER APENAS PARA PEQUENAS CORREÇÕES, MELHORIAS E ETC.)

Etapas a fazer: 

OBS: Se atentem com conflitos de merge. Trabalhem nas suas branchs e depois façam o pull request para a develop. Caso tenham algum problema com conflitos e não consigam resolver, me chamem no discord. 

@joaocastr @Rafael202074 @Dayane18

**Comment by joaocastr** [comment]
Ok

**Comment by GuiBarradas** [comment]
Etapa 3 - Finalizada

Issue editada.

**Comment by GuiBarradas** [comment]
Etapa 4 - Finalizada

Issue editada.

**Comment by joaocastr** [comment]
q isso cara. Emocionou ai?

**Comment by GuiBarradas** [comment]
ansiedade + foguete n da ré, bora 
kkkkkkkkkkkkk

**Comment by GuiBarradas** [comment]
Etapa 5 - Finalizada

Issue editada

**Comment by GuiBarradas** [comment]
Etapa 6 - Finalizada

Issue editada.

**Comment by GuiBarradas** [comment]
Etapa 7 - Finalizada

Issue editada.

**Comment by GuiBarradas** [comment]
Etapa 8 - Finalizada

Issue editada.

**Comment by GuiBarradas** [comment]
Faltam apenas a criação das duas últimas etapas. Com isso, começarão os testes e as melhorias. Lembrando, o escopo esta terminado, mas os detalhes não. Chequem, testem e façam às mudanças que acharem necessárias para o _"upgrade"_ do nosso projeto.

**Comment by GuiBarradas** [comment]
Etapa 9 e 10 finalizadas.

Issue editada e fechada.

Processo de formatação final iniciado.
